#pragma once 

#include <assert.h>
#include <iostream>

/* Test headers */
#include "profile.h"
#include "read_csv.h"

#include "domain.h"

DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_COORD_X)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_COORD_Y)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_J)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_JI)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_RX)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SY)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_CRR)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_CSS)