#pragma once 

#include <assert.h>
#include <iostream>

/* Test headers */
#include "profile.h"
#include "read_csv.h"

#include "domain.h"
#include "physical.h"
#include "numerical.h"

DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_COORD_X)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_COORD_Y)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_J)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_JI)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_RX)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SY)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_CRR)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_CSS)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_ETA)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_MU_FACE_2)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SURFACE_JACOBIAN_FACE_1)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SURFACE_JACOBIAN_FACE_2)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SURFACE_JACOBIAN_FACE_3)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_SURFACE_JACOBIAN_FACE_4)
DECLARE_PROFILE(TEST_INITIAL_CONDITIONS)

/*
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NX1)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NX2)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NX3)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NX4)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NY1)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NY2)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NY3)
DECLARE_PROFILE(TEST_TEST_INPUT_METRICS_NY4)
*/