#!/bin/bash
#SBATCH --partition=computelong ### Partition
#SBATCH --job-name=POISSON-2D-MKL     ### Job Name
#SBATCH --time=10:00:00         ### WallTime
#SBATCH --nodes=1               ### Number of Nodes
#SBATCH --ntasks=1    ### Number of tasks (MPI processes)
#SBATCH --cpus-per-task=56    
#SBATCH --account=hpctensor        ### Account used for job submission
#SBATCH --mem=400gb

export OMP_MAX_ACTIVE_LEVELS=10
export OMP_NUM_THREADS=14

mpirun -np 1 ./lab-mkl $1 $2
